name: Run tsc with eslint on all files

run-name: ${{ github.actor }} is running this job

on:
  push:
    branches:
      - main
      - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.14.2'

      - name: Install dependencies
        run: npm ci

      - name: Run tsc
        run: npm run typecheck

      - name: Run eslint
        run: npm run eslint
